### ISSUE TITLE
dart:cli documentation is missing

### ISSUE THREAD

**Issue by Hixie** [dart-lang/api.dart.dev#81] opened 2020-12-21 20:03 UTC
The https://api.dart.dev/ documentation is missing the "dart:cli" package.
It still exists, as demonstrated by running this program:

```dart
import 'dart:cli';
void main() => print(waitFor);
```

It used to be documented, for example, you can Google around and find this: https://api.dart.dev/stable/2.1.0/dart-cli/dart-cli-library.html

**Comment by kwalrath** [comment] 2021-01-05 18:46
Not sure whether this should be in the sdk repo or api.dart.dev repo... feel free to bounce it back. :)

**Comment by kwalrath** [comment] 2021-01-07 18:36
@devoncarew who'd be a good person to take this on?

**Comment by devoncarew** [comment] 2021-01-07 18:51
This is by design; `dart:cli` is just one method, w/ a bunch of controversy about whether we should have shipped a one-method top-level core library.

cc @mit-mit 

I believe this is WIA.

**Comment by Hixie** [comment] 2021-01-07 19:14
Having a secret method seems really weird. We should either decide we don't want this API and remove it, or we should document it, IMHO. Right now we're in a weird situation where the API exists and people ask questions about it but to answer their questions we have to point them to old API docs even though it still exists.

**Comment by mit-mit** [comment] 2021-01-08 11:32
It's not secret, but it is experimental, hence it's not in the stable API docs.

I agree we should work towards either graduating it from being an experiment, or deprecate and then discontinue it.

**Comment by Hixie** [comment] 2021-01-08 20:36
Right now it looks like a fully supported feature we forgot to document (or worse, which we did document but then the documentation broke). If we want to describe it as an experiment we should document it but say "this is experimental".

**Comment by Hixie** [comment] 2021-09-26 23:16
I would like to escalate this. We should either document it or remove it but having undocumented features is IMHO not an acceptable middle ground.

**Comment by Hixie** [comment] 2021-09-26 23:17
cc @leafpetersen

**Comment by Hixie** [comment] 2021-09-26 23:17
(see also https://github.com/dart-lang/sdk/issues/39390)

**Comment by aam** [comment] 2021-09-27 17:05
https://dart-review.googlesource.com/c/sdk/+/210125 landed some time ago that did 'deprecate the `dart:cli` library and `waitFor` method.'

**Comment by mit-mit** [comment] 2021-09-28 14:55
Updating in https://dart-review.googlesource.com/c/sdk/+/214620

**Comment by mit-mit** [comment] 2022-09-14 19:55
This was fixed a while back

**Closed by mit-mit** 2022-09-14 19:55 UTC
